// ================================================================
// PITCH — Player Names Database
// Used for autocomplete + fuzzy matching
// Layer A: All names, no clues needed
// 500+ players across all countries
// ================================================================

const PLAYER_ALIASES = {
  "MS Dhoni": ["msd","dhoni","mahendra singh dhoni","mahendra dhoni","ms dhoni","captain cool","captain dhoni","mahi"],
  "Sachin Tendulkar": ["sachin","tendulkar","master blaster","little master","god of cricket","sachin tendulkar"],
  "Virat Kohli": ["kohli","king kohli","chiku","virat"],
  "Rohit Sharma": ["rohit","hitman","ro","rohit sharma"],
  "Kapil Dev": ["kapil","haryana hurricane","kapil dev"],
  "Sunil Gavaskar": ["gavaskar","sunny","little master","sunil"],
  "Rahul Dravid": ["dravid","the wall","jammy","rahul dravid","the great wall"],
  "Sourav Ganguly": ["ganguly","dada","prince of kolkata","sourav"],
  "Anil Kumble": ["kumble","jumbo","anil kumble"],
  "Harbhajan Singh": ["harbhajan","bhajji","turbanator","harbhajan singh"],
  "Yuvraj Singh": ["yuvi","yuvraj"],
  "Jasprit Bumrah": ["bumrah","jasprit"],
  "R Ashwin": ["ashwin","ravi ashwin","ravichandran ashwin"],
  "Ravindra Jadeja": ["jadeja","sir jadeja","jaddu","ravindra jadeja"],
  "Virender Sehwag": ["sehwag","nawab of najafgarh","viru","virender"],
  "VVS Laxman": ["laxman","very very special","vvs laxman"],
  "Zaheer Khan": ["zaheer","zak"],
  "Irfan Pathan": ["irfan","irfan pathan"],
  "Rishabh Pant": ["pant","rishabh"],
  "Mohammed Shami": ["shami","mohammed shami","md shami"],
  "Hardik Pandya": ["hardik","pandya"],
  "Shubman Gill": ["gill","shubman"],
  "KL Rahul": ["kl rahul","rahul","lokesh rahul","k l rahul"],
  "Cheteshwar Pujara": ["pujara","cheteshwar"],
  "Mohammed Siraj": ["siraj","mohammed siraj","md siraj"],
  "Umesh Yadav": ["umesh","umesh yadav"],
  "Bhuvneshwar Kumar": ["bhuvi","bhuvneshwar","bhuvneshwar kumar"],
  "Axar Patel": ["axar","axar patel"],
  "Washington Sundar": ["washington","sundar","washington sundar"],
  "Shreyas Iyer": ["shreyas","iyer","shreyas iyer"],
  "Sanju Samson": ["sanju","samson","sanju samson"],
  "Ishan Kishan": ["ishan","kishan","ishan kishan"],
  "Suryakumar Yadav": ["surya","sky","suryakumar","suryakumar yadav"],
  "Deepak Chahar": ["deepak chahar","deepak","chahar"],
  "Prasidh Krishna": ["prasidh","krishna","prasidh krishna"],
  "Shardul Thakur": ["shardul","thakur","lord shardul","shardul thakur"],
  "Navdeep Saini": ["navdeep","saini","navdeep saini"],
  "Kuldeep Yadav": ["kuldeep","chinaman","kuldeep yadav"],
  "Yuzvendra Chahal": ["chahal","yuzi","yuzvendra","yuzvendra chahal"],
  "Dinesh Karthik": ["dk","dinesh karthik","karthik"],
  "Wriddhiman Saha": ["saha","wriddhiman","wriddhiman saha"],
  "Ajinkya Rahane": ["rahane","ajinkya","ajinkya rahane"],
  "Rohit Pawar": ["rohit pawar"],
  "Mayank Agarwal": ["mayank","mayank agarwal"],
  "Prithvi Shaw": ["prithvi","shaw","prithvi shaw"],
  "Ruturaj Gaikwad": ["ruturaj","gaikwad","ruturaj gaikwad"],
  "Tilak Varma": ["tilak","tilak varma"],
  "Yashasvi Jaiswal": ["jaiswal","yashasvi","yashasvi jaiswal"],
  "Rinku Singh": ["rinku","rinku singh"],
  "Arshdeep Singh": ["arshdeep","arshdeep singh"],
  "Don Bradman": ["bradman","the don","sir donald bradman","donald bradman"],
  "Shane Warne": ["warne","warney","king of spin","shane warne"],
  "Brian Lara": ["lara","prince of trinidad","brian lara"],
  "Muttiah Muralitharan": ["murali","muralitharan","muttiah muralitharan"],
  "Ricky Ponting": ["ponting","punter","ricky ponting"],
  "Wasim Akram": ["wasim","sultan of swing","wasim akram"],
  "Glenn McGrath": ["mcgrath","pigeon","glenn mcgrath"],
  "AB de Villiers": ["abd","mr 360","ab de villiers","abraham de villiers"],
  "Kumar Sangakkara": ["sanga","sangakkara","kumar sangakkara"],
  "Jacques Kallis": ["kallis","jacques kallis"],
  "Chris Gayle": ["gayle","universe boss","chris gayle"],
  "Adam Gilchrist": ["gilchrist","gilly","adam gilchrist"],
  "Imran Khan": ["imran","imran khan"],
  "Shoaib Akhtar": ["shoaib","rawalpindi express","shoaib akhtar"],
  "Steve Waugh": ["steve waugh","iceman","waugh"],
  "Viv Richards": ["viv","master blaster","sir vivian","viv richards","vivian richards"],
  "Garfield Sobers": ["sobers","garry sobers","sir garfield","gary sobers"],
  "Malcolm Marshall": ["marshall","malcolm marshall"],
  "Curtly Ambrose": ["ambrose","curtly ambrose"],
  "Ian Botham": ["botham","beefy","both","ian botham"],
  "Sanath Jayasuriya": ["jayasuriya","sanath","sanath jayasuriya"],
  "Mahela Jayawardene": ["mahela","jayawardene","mahela jayawardene"],
  "Daniel Vettori": ["vettori","daniel vettori"],
  "Brendon McCullum": ["mccullum","baz","bazball","brendon mccullum"],
  "Kane Williamson": ["williamson","kane williamson"],
  "Dale Steyn": ["steyn","dale steyn"],
  "Graeme Smith": ["graeme smith","smith"],
  "Shakib Al Hasan": ["shakib","shakib al hasan","shakib hasan"],
  "Babar Azam": ["babar","babar azam"],
  "Younis Khan": ["younis","younis khan"],
  "Inzamam-ul-Haq": ["inzamam","inzi","inzamam ul haq"],
  "Saeed Anwar": ["saeed anwar","anwar"],
  "Lasith Malinga": ["malinga","lasith malinga","slinga malinga"],
  "Chaminda Vaas": ["vaas","chaminda vaas"],
  "Arjuna Ranatunga": ["ranatunga","arjuna ranatunga"],
  "Richard Hadlee": ["hadlee","sir richard hadlee","richard hadlee"],
  "Kevin Pietersen": ["pietersen","kp","kevin pietersen"],
  "Andrew Flintoff": ["flintoff","freddie","fred","andrew flintoff"],
  "Joe Root": ["root","joe root"],
  "Steve Smith": ["steve smith"],
  "Faf du Plessis": ["faf","du plessis","faf du plessis"],
  "Kagiso Rabada": ["rabada","kg","kagiso rabada"],
  "Shahid Afridi": ["afridi","boom boom","shahid afridi","lala"],
  "Zaheer Abbas": ["zaheer abbas","asian bradman"],
  "Clive Lloyd": ["clive lloyd","super cat","lloyd"],
  "Michael Clarke": ["clarke","pup","michael clarke"],
  "Jonty Rhodes": ["jonty","jonty rhodes"],
  "Mark Waugh": ["mark waugh","junior"],
  "Waqar Younis": ["waqar","waqar younis"],
  "Saqlain Mushtaq": ["saqlain","saqlain mushtaq"],
  "Michael Holding": ["holding","whispering death","michael holding"],
  "Joel Garner": ["garner","big bird","joel garner"],
  "Clive Rice": ["clive rice","rice"],
  "Graeme Pollock": ["pollock","graeme pollock"],
  "Barry Richards": ["barry richards","barry"],
  "Suresh Raina": ["raina","mr ipl","suresh raina"],
  "Gautam Gambhir": ["gambhir","gautam","gautam gambhir"],
  "Murali Vijay": ["murali vijay","vijay"],
  "Shikhar Dhawan": ["dhawan","gabbar","shikhar","shikhar dhawan"],
  "Ravindra Jadeja": ["jadeja","sir jadeja"],
  "Amit Mishra": ["amit mishra","mishra"],
  "Pragyan Ojha": ["ojha","pragyan ojha"],
  "Ashish Nehra": ["nehra","ashish nehra"],
  "Venkatesh Prasad": ["venkatesh prasad","prasad"],
  "Javagal Srinath": ["srinath","javagal srinath"],
  "Ajit Agarkar": ["agarkar","ajit agarkar"],
  "Saurav Ganguly": ["saurav ganguly"],
  "Nayan Mongia": ["mongia","nayan mongia"],
  "Syed Kirmani": ["kirmani","syed kirmani"],
  "Farokh Engineer": ["engineer","farokh engineer"],
  "Chandu Borde": ["borde","chandu borde"],
  "Polly Umrigar": ["umrigar","polly umrigar"],
  "Vijay Hazare": ["vijay hazare","hazare"],
  "Lala Amarnath": ["amarnath","lala amarnath"],
  "Vinoo Mankad": ["mankad","vinoo mankad"],
  "Vijay Merchant": ["merchant","vijay merchant"],
  "CK Nayudu": ["nayudu","ck nayudu"],
  "Ravi Shastri": ["shastri","ravi shastri"],
  "Dilip Vengsarkar": ["vengsarkar","dilip vengsarkar","colonel"],
  "Sanjay Manjrekar": ["manjrekar","sanjay manjrekar"],
  "Mohinder Amarnath": ["mohinder amarnath","jimmy amarnath"],
  "Krishan Srikkanth": ["srikkanth","krishna srikkanth","kris srikkanth"],
  "Sandeep Patil": ["sandeep patil","patil"],
  "Roger Binny": ["binny","roger binny"],
  "Madan Lal": ["madan lal"],
  "Balwinder Sandhu": ["sandhu","balwinder sandhu"],
  "Tim Southee": ["southee","tim southee"],
  "Trent Boult": ["boult","trent boult"],
  "Ross Taylor": ["taylor","ross taylor","l rpl taylor"],
  "Martin Crowe": ["crowe","martin crowe"],
  "Chris Cairns": ["cairns","chris cairns"],
  "Jacob Oram": ["oram","jacob oram"],
  "Nathan Astle": ["astle","nathan astle"],
  "Stephen Fleming": ["fleming","stephen fleming"],
  "Scott Styris": ["styris","scott styris"],
  "Daryl Tuffey": ["tuffey","daryl tuffey"],
  "Dion Nash": ["dion nash","nash"],
  "Adam Parore": ["parore","adam parore"],
  "Mark Greatbatch": ["greatbatch","mark greatbatch"],
  "Andrew Jones": ["andrew jones"],
  "Jeff Crowe": ["jeff crowe"],
  "Lance Cairns": ["lance cairns"],
  "Bevan Congdon": ["congdon","bevan congdon"],
  "Glenn Turner": ["turner","glenn turner"],
  "Geoff Howarth": ["howarth","geoff howarth"],
  "Tony Greig": ["tony greig","greig"],
  "David Gower": ["gower","david gower"],
  "Graham Gooch": ["gooch","graham gooch"],
  "Geoff Boycott": ["boycott","geoff boycott"],
  "Mike Gatting": ["gatting","mike gatting"],
  "Alec Stewart": ["stewart","alec stewart"],
  "Graham Thorpe": ["thorpe","graham thorpe"],
  "Nasser Hussain": ["hussain","nasser hussain"],
  "Michael Vaughan": ["vaughan","michael vaughan"],
  "Marcus Trescothick": ["trescothick","marcus trescothick"],
  "Matthew Hoggard": ["hoggard","matthew hoggard"],
  "Darren Gough": ["gough","darren gough"],
  "Phil Tufnell": ["tufnell","phil tufnell","the cat"],
  "Derek Underwood": ["underwood","deadly","derek underwood"],
  "Bob Willis": ["willis","bob willis"],
  "John Snow": ["john snow","snow"],
  "Fred Trueman": ["trueman","fred trueman","fiery fred"],
  "Alastair Cook": ["cook","alastair cook","chef"],
  "Stuart Broad": ["broad","stuart broad"],
  "James Anderson": ["anderson","jimmy anderson","james anderson"],
  "Graeme Swann": ["swann","graeme swann"],
  "Paul Collingwood": ["collingwood","paul collingwood"],
  "Ben Stokes": ["stokes","baz stokes","ben stokes"],
  "Jonny Bairstow": ["bairstow","jonny bairstow"],
  "Jos Buttler": ["buttler","jos buttler"],
  "Sam Curran": ["curran","sam curran"],
  "Jofra Archer": ["archer","jofra archer"],
  "Mark Wood": ["mark wood","wood"],
  "Ollie Pope": ["pope","ollie pope"],
  "Harry Brook": ["brook","harry brook"],
  "Zak Crawley": ["crawley","zak crawley"],
  "Ben Duckett": ["duckett","ben duckett"],
  "Hanif Mohammad": ["hanif","hanif mohammad","little master"],
  "Javed Miandad": ["miandad","javed miandad"],
  "Mushtaq Mohammad": ["mushtaq","mushtaq mohammad"],
  "Asif Iqbal": ["asif iqbal"],
  "Majid Khan": ["majid khan","majid"],
  "Zaheer Abbas": ["zaheer abbas"],
  "Sarfraz Nawaz": ["sarfraz nawaz","sarfraz"],
  "Iqbal Qasim": ["iqbal qasim","qasim"],
  "Abdul Qadir": ["qadir","sultan of leg spin","abdul qadir"],
  "Moin Khan": ["moin","moin khan"],
  "Rashid Latif": ["rashid latif","latif"],
  "Mohammad Yousuf": ["yousuf","mohammad yousuf"],
  "Yousuf Youhana": ["yousuf youhana"],
  "Salim Malik": ["salim malik","slim"],
  "Aamir Sohail": ["aamir sohail"],
  "Saeed Anwar": ["saeed anwar"],
  "Ijaz Ahmed": ["ijaz ahmed","ijaz"],
  "Taufeeq Umar": ["taufeeq","taufeeq umar"],
  "Kamran Akmal": ["kamran akmal","kamran"],
  "Umar Akmal": ["umar akmal","umar"],
  "Mohammad Hafeez": ["hafeez","professor","mohammad hafeez"],
  "Misbah-ul-Haq": ["misbah","tuk tuk","misbah ul haq"],
  "Asad Shafiq": ["asad shafiq","asad"],
  "Azhar Ali": ["azhar ali","azhar"],
  "Ahmad Shahzad": ["ahmad shahzad"],
  "Fawad Alam": ["fawad alam","fawad"],
  "Shan Masood": ["shan masood","shan"],
  "Abdullah Shafique": ["abdullah shafique","abdullah"],
  "Imam-ul-Haq": ["imam","imam ul haq"],
  "Fakhar Zaman": ["fakhar","fakhar zaman"],
  "Mohammad Rizwan": ["rizwan","mohammad rizwan"],
  "Shadab Khan": ["shadab","shadab khan"],
  "Haris Rauf": ["haris rauf","haris"],
  "Naseem Shah": ["naseem","naseem shah"],
  "Shaheen Shah Afridi": ["shaheen","shaheen afridi","shaheen shah afridi"],
  "Mohammad Amir": ["amir","mohammad amir"],
  "Umar Gul": ["umar gul"],
  "Danish Kaneria": ["danish kaneria","danish"],
  "Mushtaq Ahmed": ["mushtaq ahmed"],
  "Anil Dalpat": ["dalpat","anil dalpat"],
  "Zaheer Abbas": ["zaheer"],
  "Desmond Haynes": ["haynes","desmond haynes"],
  "Gordon Greenidge": ["greenidge","gordon greenidge"],
  "Rohan Kanhai": ["kanhai","rohan kanhai"],
  "Lance Gibbs": ["gibbs","lance gibbs"],
  "Wes Hall": ["hall","wes hall"],
  "Charlie Griffith": ["griffith","charlie griffith"],
  "Roy Fredericks": ["fredericks","roy fredericks"],
  "Alvin Kallicharran": ["kallicharran","alvin kallicharran"],
  "Lawrence Rowe": ["lawrence rowe","rowe"],
  "Jeff Dujon": ["dujon","jeff dujon"],
  "Carl Hooper": ["hooper","carl hooper"],
  "Jimmy Adams": ["jimmy adams","adams"],
  "Shivnarine Chanderpaul": ["chanderpaul","shivnarine chanderpaul"],
  "Ramnaresh Sarwan": ["sarwan","ramnaresh sarwan"],
  "Chris Gayle": ["gayle"],
  "Marlon Samuels": ["samuels","marlon samuels"],
  "Dwayne Bravo": ["bravo","dwayne bravo","dj bravo","champion"],
  "Kieron Pollard": ["pollard","kieron pollard"],
  "Sunil Narine": ["narine","sunil narine"],
  "Jason Holder": ["holder","jason holder"],
  "Darren Bravo": ["darren bravo"],
  "Shai Hope": ["shai hope","hope"],
  "Kemar Roach": ["roach","kemar roach"],
  "Shannon Gabriel": ["gabriel","shannon gabriel"],
  "Alzarri Joseph": ["alzarri","joseph","alzarri joseph"],
  "Shimron Hetmyer": ["hetmyer","shimron hetmyer"],
  "Nicholas Pooran": ["pooran","nicholas pooran"],
  "Kyle Mayers": ["mayers","kyle mayers"],
  "Kraigg Brathwaite": ["brathwaite","kraigg brathwaite"],
  "Roston Chase": ["chase","roston chase"],
  "Evin Lewis": ["evin lewis","lewis"],
  "Mushfiqur Rahim": ["mushfiq","mushfiqur rahim","mushfiqur","rahim"],
  "Tamim Iqbal": ["tamim","tamim iqbal"],
  "Mashrafe Mortaza": ["mashrafe","mortaza","mashrafe mortaza"],
  "Rubel Hossain": ["rubel","rubel hossain"],
  "Taskin Ahmed": ["taskin","taskin ahmed"],
  "Mustafizur Rahman": ["mustafizur","fizz","mustafizur rahman"],
  "Mehidy Hasan": ["mehidy","mehidy hasan"],
  "Liton Das": ["liton","liton das"],
  "Najmul Hossain Shanto": ["shanto","najmul shanto"],
  "Mahmudul Hasan Joy": ["joy","mahmudul joy"],
  "Nurul Hasan": ["nurul","nurul hasan"],
  "Asghar Afghan": ["asghar","asghar afghan"],
  "Mohammad Nabi": ["nabi","mohammad nabi"],
  "Rashid Khan": ["rashid","rashid khan"],
  "Mujeeb ur Rahman": ["mujeeb","mujeeb ur rahman"],
  "Hazratullah Zazai": ["zazai","hazratullah zazai"],
  "Rahmat Shah": ["rahmat","rahmat shah"],
  "Kumar Dharmasena": ["dharmasena","kumar dharmasena"],
  "Upul Tharanga": ["tharanga","upul tharanga"],
  "Tillakaratne Dilshan": ["dilshan","dil-scoop","tillakaratne dilshan"],
  "Angelo Mathews": ["mathews","angelo mathews"],
  "Dinesh Chandimal": ["chandimal","dinesh chandimal"],
    "Kusal Mendis": ["mendis","kusal mendis"],
  "Dimuth Karunaratne": ["karunaratne","dimuth karunaratne"],
  "Lahiru Thirimanne": ["thirimanne","lahiru thirimanne"],
  "Akila Dananjaya": ["dananjaya","akila dananjaya"],
  "Suranga Lakmal": ["lakmal","suranga lakmal"],
  "Nuwan Kulasekara": ["kulasekara","nuwan kulasekara"],
  "Rangana Herath": ["herath","rangana herath"],
  "Thisara Perera": ["thisara perera","thisara"],
  "Dushmantha Chameera": ["chameera","dushmantha chameera"],
  "Kasun Rajitha": ["rajitha","kasun rajitha"],
  "AB de Villiers": ["abde","ab","de villiers"],
  "Hashim Amla": ["amla","hashim amla","the prince"],
  "Quinton de Kock": ["de kock","quinton de kock","qdk"],
  "Temba Bavuma": ["bavuma","temba bavuma"],
  "Aiden Markram": ["markram","aiden markram"],
  "Heinrich Klaasen": ["klaasen","heinrich klaasen"],
  "David Miller": ["miller","david miller","killer miller"],
  "Marco Jansen": ["jansen","marco jansen"],
  "Gerald Coetzee": ["coetzee","gerald coetzee"],
  "Anrich Nortje": ["nortje","anrich nortje"],
  "Lungi Ngidi": ["ngidi","lungi ngidi"],
  "Andile Phehlukwayo": ["phehlukwayo","andile phehlukwayo"],
  "Tabraiz Shamsi": ["shamsi","tabraiz shamsi"],
  "Keshav Maharaj": ["maharaj","keshav maharaj"],
  "Dean Elgar": ["elgar","dean elgar"],
  "Elton Chigumbura": ["chigumbura","elton chigumbura"],
  "Brendan Taylor": ["brendan taylor","brendan"],
  "Craig Ervine": ["ervine","craig ervine"],
  "Sikandar Raza": ["raza","sikandar raza"],
  "Sean Williams": ["sean williams","williams"],
  "Blessing Muzarabani": ["muzarabani","blessing muzarabani"],
  "Tendai Chatara": ["chatara","tendai chatara"],
  "Graeme Cremer": ["cremer","graeme cremer"],
  "Kyle Abbott": ["kyle abbott","abbott"],
  "Colin Munro": ["colin munro","munro"],
  "Guptill": ["guptill","martin guptill"],
  "Martin Guptill": ["martin guptill","guptill"],
  "Tom Latham": ["latham","tom latham"],
  "Devon Conway": ["conway","devon conway"],
  "Daryl Mitchell": ["daryl mitchell","mitchell"],
  "Glenn Phillips": ["phillips","glenn phillips"],
  "Matt Henry": ["matt henry","henry"],
  "Mitchell Santner": ["santner","mitchell santner"],
  "Lockie Ferguson": ["lockie","lockie ferguson","ferguson"],
  "Kyle Jamieson": ["jamieson","kyle jamieson"],
  "Ish Sodhi": ["sodhi","ish sodhi"],
  "Todd Astle": ["todd astle"],
  "BJ Watling": ["watling","bj watling"],
  "Luke Ronchi": ["ronchi","luke ronchi"],
  "Peter Fulton": ["fulton","peter fulton"],
  "Mathew Sinclair": ["sinclair","mathew sinclair"],
  "Chris Harris": ["chris harris","harris"],
  "Dion Nash": ["dion nash"],
  "Simon Doull": ["doull","simon doull"],
  "Matthew Hayden": ["hayden","matthew hayden"],
  "Justin Langer": ["langer","justin langer"],
  "Damien Martyn": ["martyn","damien martyn"],
  "Michael Hussey": ["hussey","mr cricket","michael hussey"],
  "Andrew Symonds": ["symonds","roy","andrew symonds"],
  "Shane Watson": ["watson","shane watson"],
  "Mitchell Johnson": ["mitchell johnson","mitch johnson"],
  "Ryan Harris": ["ryan harris"],
  "Peter Siddle": ["siddle","peter siddle"],
  "Mitchell Starc": ["starc","mitchell starc"],
  "Josh Hazlewood": ["hazlewood","josh hazlewood"],
  "Nathan Lyon": ["lyon","nathan lyon","gazza","the gfg"],
  "Pat Cummins": ["cummins","pat cummins"],
  "David Warner": ["warner","david warner"],
  "Aaron Finch": ["finch","aaron finch"],
  "Travis Head": ["head","travis head"],
  "Marnus Labuschagne": ["labuschagne","marnus labuschagne","marnus"],
  "Steven Smith": ["smith","steven smith"],
  "Alex Carey": ["carey","alex carey"],
  "Cameron Green": ["green","cameron green"],
  "Scott Boland": ["boland","scott boland"],
  "Adam Zampa": ["zampa","adam zampa"],
  "Matthew Wade": ["wade","matthew wade"],
  "Glenn Maxwell": ["maxwell","maxi","big show","glenn maxwell"],
  "Marcus Stoinis": ["stoinis","marcus stoinis"],
  "Ashton Agar": ["agar","ashton agar"],
  "Tim Paine": ["paine","tim paine"],
  "Peter Nevill": ["nevill","peter nevill"],
  "Brad Haddin": ["haddin","brad haddin"],
  "Ian Healy": ["healy","ian healy"],
  "Rod Marsh": ["marsh","rod marsh"],
  "Ian Chappell": ["ian chappell","chappell"],
  "Greg Chappell": ["greg chappell"],
  "Doug Walters": ["walters","doug walters"],
  "Bill Lawry": ["lawry","bill lawry"],
  "Bob Simpson": ["bob simpson","simpson"],
  "Neil Harvey": ["neil harvey","harvey"],
  "Keith Miller": ["keith miller"],
  "Ray Lindwall": ["lindwall","ray lindwall"],
  "Dennis Lillee": ["lillee","dennis lillee"],
  "Jeff Thomson": ["thomson","jeff thomson"],
  "Graeme Wood": ["graeme wood"],
  "Kim Hughes": ["hughes","kim hughes"],
  "Allan Border": ["border","ab border","allan border"],
  "Mark Taylor": ["mark taylor"],
};

// All player names for lookup — 500+ players
const ALL_PLAYERS = [
  // India
  {n:"Sachin Tendulkar",c:"India"},{n:"MS Dhoni",c:"India"},{n:"Virat Kohli",c:"India"},
  {n:"Rohit Sharma",c:"India"},{n:"Kapil Dev",c:"India"},{n:"Sunil Gavaskar",c:"India"},
  {n:"Rahul Dravid",c:"India"},{n:"Sourav Ganguly",c:"India"},{n:"Anil Kumble",c:"India"},
  {n:"Virender Sehwag",c:"India"},{n:"Harbhajan Singh",c:"India"},{n:"Yuvraj Singh",c:"India"},
  {n:"Jasprit Bumrah",c:"India"},{n:"R Ashwin",c:"India"},{n:"Ravindra Jadeja",c:"India"},
  {n:"VVS Laxman",c:"India"},{n:"Zaheer Khan",c:"India"},{n:"Irfan Pathan",c:"India"},
  {n:"Rishabh Pant",c:"India"},{n:"Mohammed Shami",c:"India"},{n:"Hardik Pandya",c:"India"},
  {n:"Shubman Gill",c:"India"},{n:"KL Rahul",c:"India"},{n:"Cheteshwar Pujara",c:"India"},
  {n:"Mohammed Siraj",c:"India"},{n:"Umesh Yadav",c:"India"},{n:"Bhuvneshwar Kumar",c:"India"},
  {n:"Axar Patel",c:"India"},{n:"Washington Sundar",c:"India"},{n:"Shreyas Iyer",c:"India"},
  {n:"Sanju Samson",c:"India"},{n:"Ishan Kishan",c:"India"},{n:"Suryakumar Yadav",c:"India"},
  {n:"Deepak Chahar",c:"India"},{n:"Prasidh Krishna",c:"India"},{n:"Shardul Thakur",c:"India"},
  {n:"Kuldeep Yadav",c:"India"},{n:"Yuzvendra Chahal",c:"India"},{n:"Dinesh Karthik",c:"India"},
  {n:"Wriddhiman Saha",c:"India"},{n:"Ajinkya Rahane",c:"India"},{n:"Mayank Agarwal",c:"India"},
  {n:"Prithvi Shaw",c:"India"},{n:"Ruturaj Gaikwad",c:"India"},{n:"Tilak Varma",c:"India"},
  {n:"Yashasvi Jaiswal",c:"India"},{n:"Rinku Singh",c:"India"},{n:"Arshdeep Singh",c:"India"},
  {n:"Suresh Raina",c:"India"},{n:"Gautam Gambhir",c:"India"},{n:"Shikhar Dhawan",c:"India"},
  {n:"Murali Vijay",c:"India"},{n:"Amit Mishra",c:"India"},{n:"Pragyan Ojha",c:"India"},
  {n:"Ashish Nehra",c:"India"},{n:"Javagal Srinath",c:"India"},{n:"Venkatesh Prasad",c:"India"},
  {n:"Ajit Agarkar",c:"India"},{n:"Ravi Shastri",c:"India"},{n:"Dilip Vengsarkar",c:"India"},
  {n:"Mohinder Amarnath",c:"India"},{n:"Sandeep Patil",c:"India"},{n:"Roger Binny",c:"India"},
  {n:"Madan Lal",c:"India"},{n:"Syed Kirmani",c:"India"},{n:"Farokh Engineer",c:"India"},
  {n:"Polly Umrigar",c:"India"},{n:"Vijay Hazare",c:"India"},{n:"Lala Amarnath",c:"India"},
  {n:"Vinoo Mankad",c:"India"},{n:"Vijay Merchant",c:"India"},{n:"CK Nayudu",c:"India"},
  {n:"Nawab of Pataudi",c:"India"},{n:"Chandu Borde",c:"India"},{n:"Abbas Ali Baig",c:"India"},
  {n:"Sanjay Manjrekar",c:"India"},{n:"Krishan Srikkanth",c:"India"},{n:"Balwinder Sandhu",c:"India"},
  {n:"Navdeep Saini",c:"India"},{n:"Deepak Hooda",c:"India"},{n:"Khaleel Ahmed",c:"India"},
  {n:"Hanuma Vihari",c:"India"},{n:"Ishant Sharma",c:"India"},{n:"Nayan Mongia",c:"India"},

  // Australia
  {n:"Don Bradman",c:"Australia"},{n:"Ricky Ponting",c:"Australia"},{n:"Shane Warne",c:"Australia"},
  {n:"Glenn McGrath",c:"Australia"},{n:"Adam Gilchrist",c:"Australia"},{n:"Steve Waugh",c:"Australia"},
  {n:"Matthew Hayden",c:"Australia"},{n:"Justin Langer",c:"Australia"},{n:"Michael Clarke",c:"Australia"},
  {n:"Andrew Symonds",c:"Australia"},{n:"Michael Hussey",c:"Australia"},{n:"Shane Watson",c:"Australia"},
  {n:"Mitchell Johnson",c:"Australia"},{n:"David Warner",c:"Australia"},{n:"Steven Smith",c:"Australia"},
  {n:"Mitchell Starc",c:"Australia"},{n:"Josh Hazlewood",c:"Australia"},{n:"Pat Cummins",c:"Australia"},
  {n:"Nathan Lyon",c:"Australia"},{n:"Glenn Maxwell",c:"Australia"},{n:"Aaron Finch",c:"Australia"},
  {n:"Travis Head",c:"Australia"},{n:"Marnus Labuschagne",c:"Australia"},{n:"Alex Carey",c:"Australia"},
  {n:"Cameron Green",c:"Australia"},{n:"Scott Boland",c:"Australia"},{n:"Adam Zampa",c:"Australia"},
  {n:"Ian Healy",c:"Australia"},{n:"Rod Marsh",c:"Australia"},{n:"Ian Chappell",c:"Australia"},
  {n:"Greg Chappell",c:"Australia"},{n:"Dennis Lillee",c:"Australia"},{n:"Jeff Thomson",c:"Australia"},
  {n:"Allan Border",c:"Australia"},{n:"Mark Taylor",c:"Australia"},{n:"Damien Martyn",c:"Australia"},
  {n:"Brad Haddin",c:"Australia"},{n:"Marcus Stoinis",c:"Australia"},{n:"Tim Paine",c:"Australia"},

  // England
  {n:"Ian Botham",c:"England"},{n:"Kevin Pietersen",c:"England"},{n:"Andrew Flintoff",c:"England"},
  {n:"Joe Root",c:"England"},{n:"Alastair Cook",c:"England"},{n:"Stuart Broad",c:"England"},
  {n:"James Anderson",c:"England"},{n:"Ben Stokes",c:"England"},{n:"Jonny Bairstow",c:"England"},
  {n:"Jos Buttler",c:"England"},{n:"Graeme Swann",c:"England"},{n:"Michael Vaughan",c:"England"},
  {n:"Nasser Hussain",c:"England"},{n:"Graham Gooch",c:"England"},{n:"Geoff Boycott",c:"England"},
  {n:"David Gower",c:"England"},{n:"Derek Underwood",c:"England"},{n:"Fred Trueman",c:"England"},
  {n:"Bob Willis",c:"England"},{n:"Tony Greig",c:"England"},{n:"Mike Gatting",c:"England"},
  {n:"Alec Stewart",c:"England"},{n:"Graham Thorpe",c:"England"},{n:"Marcus Trescothick",c:"England"},
  {n:"Jofra Archer",c:"England"},{n:"Sam Curran",c:"England"},{n:"Mark Wood",c:"England"},
  {n:"Ollie Pope",c:"England"},{n:"Harry Brook",c:"England"},{n:"Zak Crawley",c:"England"},
  {n:"Ben Duckett",c:"England"},{n:"Phil Tufnell",c:"England"},{n:"Paul Collingwood",c:"England"},

  // West Indies
  {n:"Brian Lara",c:"West Indies"},{n:"Viv Richards",c:"West Indies"},{n:"Garfield Sobers",c:"West Indies"},
  {n:"Malcolm Marshall",c:"West Indies"},{n:"Curtly Ambrose",c:"West Indies"},{n:"Chris Gayle",c:"West Indies"},
  {n:"Clive Lloyd",c:"West Indies"},{n:"Desmond Haynes",c:"West Indies"},{n:"Gordon Greenidge",c:"West Indies"},
  {n:"Joel Garner",c:"West Indies"},{n:"Michael Holding",c:"West Indies"},{n:"Rohan Kanhai",c:"West Indies"},
  {n:"Lance Gibbs",c:"West Indies"},{n:"Wes Hall",c:"West Indies"},{n:"Carl Hooper",c:"West Indies"},
  {n:"Shivnarine Chanderpaul",c:"West Indies"},{n:"Dwayne Bravo",c:"West Indies"},
  {n:"Kieron Pollard",c:"West Indies"},{n:"Sunil Narine",c:"West Indies"},{n:"Jason Holder",c:"West Indies"},
  {n:"Shai Hope",c:"West Indies"},{n:"Nicholas Pooran",c:"West Indies"},{n:"Kyle Mayers",c:"West Indies"},
  {n:"Kemar Roach",c:"West Indies"},{n:"Shannon Gabriel",c:"West Indies"},
  {n:"Alzarri Joseph",c:"West Indies"},{n:"Shimron Hetmyer",c:"West Indies"},
  {n:"Kraigg Brathwaite",c:"West Indies"},{n:"Marlon Samuels",c:"West Indies"},

  // Pakistan
  {n:"Wasim Akram",c:"Pakistan"},{n:"Imran Khan",c:"Pakistan"},{n:"Shoaib Akhtar",c:"Pakistan"},
  {n:"Waqar Younis",c:"Pakistan"},{n:"Shahid Afridi",c:"Pakistan"},{n:"Inzamam-ul-Haq",c:"Pakistan"},
  {n:"Younis Khan",c:"Pakistan"},{n:"Saeed Anwar",c:"Pakistan"},{n:"Babar Azam",c:"Pakistan"},
  {n:"Javed Miandad",c:"Pakistan"},{n:"Hanif Mohammad",c:"Pakistan"},{n:"Zaheer Abbas",c:"Pakistan"},
  {n:"Abdul Qadir",c:"Pakistan"},{n:"Mushtaq Mohammad",c:"Pakistan"},{n:"Saqlain Mushtaq",c:"Pakistan"},
  {n:"Mohammad Yousuf",c:"Pakistan"},{n:"Misbah-ul-Haq",c:"Pakistan"},{n:"Mohammad Hafeez",c:"Pakistan"},
  {n:"Kamran Akmal",c:"Pakistan"},{n:"Asad Shafiq",c:"Pakistan"},{n:"Azhar Ali",c:"Pakistan"},
  {n:"Mohammad Rizwan",c:"Pakistan"},{n:"Fakhar Zaman",c:"Pakistan"},{n:"Imam-ul-Haq",c:"Pakistan"},
  {n:"Shaheen Shah Afridi",c:"Pakistan"},{n:"Naseem Shah",c:"Pakistan"},{n:"Haris Rauf",c:"Pakistan"},
  {n:"Shadab Khan",c:"Pakistan"},{n:"Mohammad Amir",c:"Pakistan"},{n:"Umar Gul",c:"Pakistan"},
  {n:"Danish Kaneria",c:"Pakistan"},{n:"Mushtaq Ahmed",c:"Pakistan"},{n:"Shan Masood",c:"Pakistan"},

  // Sri Lanka
  {n:"Muttiah Muralitharan",c:"Sri Lanka"},{n:"Sanath Jayasuriya",c:"Sri Lanka"},
  {n:"Mahela Jayawardene",c:"Sri Lanka"},{n:"Kumar Sangakkara",c:"Sri Lanka"},
  {n:"Arjuna Ranatunga",c:"Sri Lanka"},{n:"Lasith Malinga",c:"Sri Lanka"},
  {n:"Chaminda Vaas",c:"Sri Lanka"},{n:"Daniel Vettori",c:"New Zealand"},
  {n:"Angelo Mathews",c:"Sri Lanka"},{n:"Dinesh Chandimal",c:"Sri Lanka"},
  {n:"Tillakaratne Dilshan",c:"Sri Lanka"},{n:"Upul Tharanga",c:"Sri Lanka"},
  {n:"Rangana Herath",c:"Sri Lanka"},{n:"Kusal Mendis",c:"Sri Lanka"},
  {n:"Dimuth Karunaratne",c:"Sri Lanka"},{n:"Suranga Lakmal",c:"Sri Lanka"},
  {n:"Dushmantha Chameera",c:"Sri Lanka"},{n:"Akila Dananjaya",c:"Sri Lanka"},

  // South Africa
  {n:"AB de Villiers",c:"South Africa"},{n:"Jacques Kallis",c:"South Africa"},
  {n:"Graeme Smith",c:"South Africa"},{n:"Dale Steyn",c:"South Africa"},
  {n:"Hashim Amla",c:"South Africa"},{n:"Kagiso Rabada",c:"South Africa"},
  {n:"Faf du Plessis",c:"South Africa"},{n:"Jonty Rhodes",c:"South Africa"},
  {n:"Graeme Pollock",c:"South Africa"},{n:"Barry Richards",c:"South Africa"},
  {n:"Alan Knott",c:"England"},{n:"Clive Rice",c:"South Africa"},
  {n:"Quinton de Kock",c:"South Africa"},{n:"Temba Bavuma",c:"South Africa"},
  {n:"Aiden Markram",c:"South Africa"},{n:"Heinrich Klaasen",c:"South Africa"},
  {n:"David Miller",c:"South Africa"},{n:"Anrich Nortje",c:"South Africa"},
  {n:"Keshav Maharaj",c:"South Africa"},{n:"Tabraiz Shamsi",c:"South Africa"},

  // New Zealand
  {n:"Richard Hadlee",c:"New Zealand"},{n:"Martin Crowe",c:"New Zealand"},
  {n:"Brendon McCullum",c:"New Zealand"},{n:"Kane Williamson",c:"New Zealand"},
  {n:"Ross Taylor",c:"New Zealand"},{n:"Tim Southee",c:"New Zealand"},
  {n:"Trent Boult",c:"New Zealand"},{n:"Kyle Jamieson",c:"New Zealand"},
  {n:"Martin Guptill",c:"New Zealand"},{n:"Tom Latham",c:"New Zealand"},
  {n:"Devon Conway",c:"New Zealand"},{n:"Daryl Mitchell",c:"New Zealand"},
  {n:"Glenn Phillips",c:"New Zealand"},{n:"Matt Henry",c:"New Zealand"},
  {n:"Mitchell Santner",c:"New Zealand"},{n:"Lockie Ferguson",c:"New Zealand"},
  {n:"Nathan Astle",c:"New Zealand"},{n:"Chris Cairns",c:"New Zealand"},
  {n:"Stephen Fleming",c:"New Zealand"},{n:"Daniel Vettori",c:"New Zealand"},

  // Bangladesh
  {n:"Shakib Al Hasan",c:"Bangladesh"},{n:"Tamim Iqbal",c:"Bangladesh"},
  {n:"Mushfiqur Rahim",c:"Bangladesh"},{n:"Mashrafe Mortaza",c:"Bangladesh"},
  {n:"Mustafizur Rahman",c:"Bangladesh"},{n:"Mehidy Hasan",c:"Bangladesh"},
  {n:"Liton Das",c:"Bangladesh"},{n:"Taskin Ahmed",c:"Bangladesh"},
  {n:"Rubel Hossain",c:"Bangladesh"},{n:"Najmul Hossain Shanto",c:"Bangladesh"},

  // Afghanistan
  {n:"Rashid Khan",c:"Afghanistan"},{n:"Mohammad Nabi",c:"Afghanistan"},
  {n:"Mujeeb ur Rahman",c:"Afghanistan"},{n:"Hazratullah Zazai",c:"Afghanistan"},
  {n:"Rahmat Shah",c:"Afghanistan"},{n:"Asghar Afghan",c:"Afghanistan"},

  // Zimbabwe
  {n:"Brendan Taylor",c:"Zimbabwe"},{n:"Sikandar Raza",c:"Zimbabwe"},
  {n:"Sean Williams",c:"Zimbabwe"},{n:"Craig Ervine",c:"Zimbabwe"},
  {n:"Blessing Muzarabani",c:"Zimbabwe"},{n:"Elton Chigumbura",c:"Zimbabwe"},

  // Ireland
  {n:"Kevin O'Brien",c:"Ireland"},{n:"Paul Stirling",c:"Ireland"},
  {n:"Andrew Balbirnie",c:"Ireland"},{n:"Lorcan Tucker",c:"Ireland"},
];

// Build surname map for uniqueness checks
const SURNAME_MAP = {};
ALL_PLAYERS.forEach(p => {
  const parts = p.n.split(' ');
  const surname = parts[parts.length-1].toLowerCase();
  if(!SURNAME_MAP[surname]) SURNAME_MAP[surname]=[];
  SURNAME_MAP[surname].push(p.n);
});
