// ================================================================
// PITCH — Puzzle Database
// 80 players with full clues in English + Hindi
// facts, moreFacts, quiz questions
// 55% India, 45% International
// ================================================================
const PUZZLES = [
{name:"Sachin Tendulkar",flag:"🇮🇳",country:"India",role:"Batter",
 tomorrow:{country:"India",role:"Fast bowler",era:"1970s–1990s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Right-hand bat · Tests & ODIs · Mumbai",mono:false},
      {label:"Record",type:"CLUE 2",value:"100 international centuries — world record",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 1989–2013",mono:true},
      {label:"Stats",type:"CLUE 4",value:"15,921 Test runs · 200 Tests played",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"दाएं हाथ का बल्लेबाज़ · मुंबई · टेस्ट और ODI",mono:false},
      {label:"रिकॉर्ड",type:"सुराग 2",value:"100 अंतरराष्ट्रीय शतक — विश्व रिकॉर्ड",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 1989–2013",mono:true},
      {label:"आँकड़े",type:"सुराग 4",value:"15,921 टेस्ट रन · 200 टेस्ट मैच",mono:true}]},
 stats:{matches:"200 Tests · 463 ODIs",runs:"15,921 Test runs",avg:"53.78",era:"1989–2013"},
 fact:{en:"Sachin made his Test debut against Pakistan at just 16, got hit on the nose by Waqar Younis, and refused to retire hurt.",
       hi:"सचिन ने मात्र 16 साल की उम्र में पाकिस्तान के खिलाफ टेस्ट डेब्यू किया। वकार युनुस ने उनकी नाक पर चोट मारी, लेकिन वे मैदान नहीं छोड़े।"},
 moreFacts:{en:"His 100th century came in 2012 in Dhaka after a 1-year drought the entire nation waited through. He played 24 years of international cricket.",
            hi:"उनका 100वां शतक 2012 में ढाका में आया। पूरा देश 1 साल से इंतजार कर रहा था। उन्होंने 24 साल तक अंतरराष्ट्रीय क्रिकेट खेला।"},
 quiz:[{q:{en:"In which city did Sachin score his 100th international century?",hi:"सचिन ने अपना 100वां अंतरराष्ट्रीय शतक किस शहर में बनाया?"},
        o:{en:["Mumbai","Kolkata","Dhaka","Delhi"],hi:["मुंबई","कोलकाता","ढाका","दिल्ली"]},c:2,
        exp:{en:"Sachin scored his 100th century in Dhaka against Bangladesh in the 2012 Asia Cup.",hi:"सचिन ने 2012 एशिया कप में बांग्लादेश के खिलाफ ढाका में 100वां शतक बनाया।"}},
       {q:{en:"How old was Sachin when he made his Test debut?",hi:"सचिन ने टेस्ट डेब्यू किस उम्र में किया?"},
        o:{en:["15","16","17","18"],hi:["15","16","17","18"]},c:1,
        exp:{en:"Sachin was 16 years and 205 days old at his debut — India's youngest Test player.",hi:"सचिन 16 साल 205 दिन के थे — भारत के सबसे युवा टेस्ट खिलाड़ी।"}},
       {q:{en:"How many Tests did Sachin play?",hi:"सचिन ने कितने टेस्ट मैच खेले?"},
        o:{en:["180","200","220","240"],hi:["180","200","220","240"]},c:1,
        exp:{en:"Sachin played exactly 200 Test matches — the most by any player in history.",hi:"सचिन ने ठीक 200 टेस्ट मैच खेले — किसी भी खिलाड़ी द्वारा सबसे ज़्यादा।"}}]},

{name:"MS Dhoni",flag:"🇮🇳",country:"India",role:"Wicket-keeper Batter",
 tomorrow:{country:"India",role:"Left-hand bat",era:"2000s–2010s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Wicket-keeper · Right-hand bat · Captain",mono:false},
      {label:"Trophy",type:"CLUE 2",value:"Won 2007 T20 WC, 2011 ODI WC, 2013 CT",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 2004–2019 · From Ranchi",mono:true},
      {label:"Record",type:"CLUE 4",value:"Most ODI stumpings ever: 123",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"विकेटकीपर · दाएं हाथ का बल्लेबाज़ · कप्तान",mono:false},
      {label:"ट्रॉफी",type:"सुराग 2",value:"2007 T20 WC, 2011 ODI WC, 2013 CT जीता",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 2004–2019 · रांची से",mono:true},
      {label:"रिकॉर्ड",type:"सुराग 4",value:"ODI में सबसे ज़्यादा स्टंपिंग: 123",mono:true}]},
 stats:{matches:"90 Tests · 350 ODIs",runs:"4,876 Test runs",avg:"38.09",era:"2004–2019"},
 fact:{en:"Dhoni worked as a ticket collector at Kharagpur Railway Station before cricket changed his life. He also holds an Army parachute regiment honorary rank.",
       hi:"धोनी क्रिकेट से पहले खड़गपुर रेलवे स्टेशन पर टिकट कलेक्टर थे। उन्हें भारतीय सेना के पैराशूट रेजिमेंट में मानद पद भी मिला हुआ है।"},
 moreFacts:{en:"In the 2011 World Cup final, he promoted himself above Yuvraj to bat at No.5 and hit the winning six. He never publicly explains his decisions.",
            hi:"2011 विश्व कप फाइनल में उन्होंने युवराज से पहले खुद को नंबर 5 पर भेजा और जीतने वाला छक्का लगाया। वे कभी अपने फैसले नहीं समझाते।"},
 quiz:[{q:{en:"What is MS Dhoni's famous jersey number?",hi:"MS धोनी की फेमस जर्सी नंबर क्या है?"},
        o:{en:["5","7","10","11"],hi:["5","7","10","11"]},c:1,
        exp:{en:"MS Dhoni is famous for jersey number 7 throughout his international career.",hi:"MS धोनी का जर्सी नंबर 7 उनके पूरे करियर में मशहूर रहा।"}},
       {q:{en:"Dhoni hit the World Cup winning six off which bowler?",hi:"धोनी ने विश्व कप जीतने वाला छक्का किस गेंदबाज़ पर लगाया?"},
        o:{en:["Dilhara Fernando","Nuwan Kulasekara","Lasith Malinga","Angelo Mathews"],hi:["दिलहारा फर्नांडो","नुवान कुलसेकरा","लसिथ मलिंगा","एंजेलो मैथ्यूज़"]},c:1,
        exp:{en:"Dhoni hit Nuwan Kulasekara for the famous six to win the 2011 World Cup Final at Wankhede.",hi:"धोनी ने वानखेड़े में 2011 विश्व कप फाइनल जीतने के लिए नुवान कुलसेकरा पर वो प्रसिद्ध छक्का लगाया।"}},
       {q:{en:"In which city was MS Dhoni born?",hi:"MS धोनी का जन्म किस शहर में हुआ?"},
        o:{en:["Patna","Ranchi","Jamshedpur","Dhanbad"],hi:["पटना","रांची","जमशेदपुर","धनबाद"]},c:1,
        exp:{en:"MS Dhoni was born on July 7, 1981 in Ranchi, Jharkhand.",hi:"MS धोनी का जन्म 7 जुलाई 1981 को रांची, झारखंड में हुआ।"}}]},

{name:"Virat Kohli",flag:"🇮🇳",country:"India",role:"Batter",
 tomorrow:{country:"India",role:"Opening batter",era:"2000s–2020s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Right-hand bat · All formats · Delhi",mono:false},
      {label:"Record",type:"CLUE 2",value:"50 ODI centuries — all-time world record",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 2008–present",mono:true},
      {label:"Stat",type:"CLUE 4",value:"Fastest to 10,000 ODI runs: 205 innings",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"दाएं हाथ का बल्लेबाज़ · सभी फॉर्मेट · दिल्ली",mono:false},
      {label:"रिकॉर्ड",type:"सुराग 2",value:"50 ODI शतक — विश्व रिकॉर्ड",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 2008–वर्तमान",mono:true},
      {label:"आँकड़ा",type:"सुराग 4",value:"सबसे तेज़ 10,000 ODI रन: 205 पारियों में",mono:true}]},
 stats:{matches:"113 Tests · 295 ODIs",runs:"9,230 Test runs",avg:"46.85",era:"2008–present"},
 fact:{en:"Kohli transformed his body completely — from an unfit teenager to one of the world's fittest athletes. He credits a plant-based diet shift in 2018.",
       hi:"कोहली ने अपने शरीर को पूरी तरह बदल लिया — अनफिट किशोर से दुनिया के सबसे फिट एथलीटों में से एक बन गए। 2018 में उन्होंने plant-based diet अपनाया।"},
 moreFacts:{en:"His record of 50 ODI centuries surpassed Sachin's 49. He averaged 82 in ODIs in 2018 alone — one of cricket's greatest single-year performances.",
            hi:"उनके 50 ODI शतकों का रिकॉर्ड सचिन के 49 को पार कर गया। 2018 में अकेले ODI में उनका औसत 82 था।"},
 quiz:[{q:{en:"How many ODI centuries has Kohli scored — the world record?",hi:"कोहली के ODI शतकों की संख्या — विश्व रिकॉर्ड — क्या है?"},
        o:{en:["45","48","50","52"],hi:["45","48","50","52"]},c:2,
        exp:{en:"Kohli has scored 50 ODI centuries — the most by any player in cricket history.",hi:"कोहली के 50 ODI शतक हैं — क्रिकेट इतिहास में किसी भी खिलाड़ी द्वारा सबसे ज़्यादा।"}},
       {q:{en:"Kohli scored his maiden Test century against which country?",hi:"कोहली ने पहला टेस्ट शतक किस देश के खिलाफ बनाया?"},
        o:{en:["Sri Lanka","Bangladesh","Pakistan","West Indies"],hi:["श्रीलंका","बांग्लादेश","पाकिस्तान","वेस्टइंडीज"]},c:1,
        exp:{en:"Kohli scored his first Test century against Bangladesh at Chittagong in 2010.",hi:"कोहली ने 2010 में चटगांव में बांग्लादेश के खिलाफ पहला टेस्ट शतक बनाया।"}},
       {q:{en:"How many times has Kohli won IPL with RCB?",hi:"कोहली ने RCB के साथ IPL कितनी बार जीता?"},
        o:{en:["0","1","2","3"],hi:["0","1","2","3"]},c:0,
        exp:{en:"Despite being cricket's greatest batter of his era, Kohli has never won an IPL with Royal Challengers Bangalore.",hi:"अपने दौर के सबसे महान बल्लेबाज़ होने के बावजूद, कोहली ने RCB के साथ IPL कभी नहीं जीता।"}}]},

{name:"Kapil Dev",flag:"🇮🇳",country:"India",role:"All-rounder",
 tomorrow:{country:"India",role:"Opening batter",era:"1970s–1980s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Right-arm fast · All-rounder · Haryana",mono:false},
      {label:"Wickets",type:"CLUE 2",value:"434 Test wickets — world record at retirement",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 1978–1994",mono:true},
      {label:"Trophy",type:"CLUE 4",value:"Led India to 1983 World Cup victory at Lord's",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"दाएं हाथ तेज़ · ऑलराउंडर · हरियाणा",mono:false},
      {label:"विकेट",type:"सुराग 2",value:"434 टेस्ट विकेट — रिटायरमेंट पर विश्व रिकॉर्ड",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 1978–1994",mono:true},
      {label:"ट्रॉफी",type:"सुराग 4",value:"1983 विश्व कप — लॉर्ड्स में भारत को जीत दिलाई",mono:true}]},
 stats:{matches:"131 Tests",runs:"5,248 Test runs",avg:"31.05 bat",era:"1978–1994"},
 fact:{en:"Kapil Dev's 175* against Zimbabwe in the 1983 World Cup was never broadcast — the BBC crew had gone for lunch. The greatest unrecorded innings in history.",
       hi:"1983 विश्व कप में जिम्बाब्वे के खिलाफ कपिल देव की 175* पारी कभी प्रसारित नहीं हुई — BBC की टीम दोपहर के खाने पर चली गई थी।"},
 moreFacts:{en:"Without Kapil's innings, India would have been eliminated in the group stage of 1983. He was also the first to take 400+ Test wickets and score 4000+ Test runs.",
            hi:"कपिल की पारी के बिना भारत 1983 में ग्रुप स्टेज में ही बाहर हो जाता। वे 400+ टेस्ट विकेट और 4000+ टेस्ट रन बनाने वाले पहले खिलाड़ी भी थे।"},
 quiz:[{q:{en:"What was India's total in the 1983 World Cup Final?",hi:"1983 विश्व कप फाइनल में भारत का स्कोर क्या था?"},
        o:{en:["183","175","200","150"],hi:["183","175","200","150"]},c:0,
        exp:{en:"India scored 183 all out batting first — a total that seemed inadequate, but Kapil's bowling attack dismissed West Indies for 140.",hi:"भारत ने पहले बल्लेबाज़ी करते हुए 183 रन बनाए — जो कम लग रहे थे, पर कपिल की गेंदबाज़ी ने वेस्टइंडीज को 140 पर समेट दिया।"}},
       {q:{en:"In which city was Kapil Dev born?",hi:"कपिल देव का जन्म किस शहर में हुआ?"},
        o:{en:["Delhi","Chandigarh","Amritsar","Ludhiana"],hi:["दिल्ली","चंडीगढ़","अमृतसर","लुधियाना"]},c:1,
        exp:{en:"Kapil Dev was born on January 6, 1959, in Chandigarh, Punjab.",hi:"कपिल देव का जन्म 6 जनवरी 1959 को चंडीगढ़, पंजाब में हुआ था।"}},
       {q:{en:"How many Test wickets did Kapil Dev finish with?",hi:"कपिल देव ने कुल कितने टेस्ट विकेट लिए?"},
        o:{en:["400","425","434","440"],hi:["400","425","434","440"]},c:2,
        exp:{en:"Kapil Dev retired with 434 Test wickets — a world record at the time.",hi:"कपिल देव ने 434 टेस्ट विकेट के साथ संन्यास लिया — उस समय विश्व रिकॉर्ड।"}}]},

{name:"Sunil Gavaskar",flag:"🇮🇳",country:"India",role:"Batter",
 tomorrow:{country:"India",role:"Middle-order batter",era:"1990s–2010s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Opening batter · Right-hand · Maharashtra",mono:false},
      {label:"Record",type:"CLUE 2",value:"34 Test centuries — then world record",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 1971–1987",mono:true},
      {label:"Milestone",type:"CLUE 4",value:"First player in history to score 10,000 Test runs",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"ओपनिंग बल्लेबाज़ · दाएं हाथ · महाराष्ट्र",mono:false},
      {label:"रिकॉर्ड",type:"सुराग 2",value:"34 टेस्ट शतक — तत्कालीन विश्व रिकॉर्ड",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 1971–1987",mono:true},
      {label:"उपलब्धि",type:"सुराग 4",value:"टेस्ट में 10,000 रन बनाने वाले इतिहास के पहले खिलाड़ी",mono:true}]},
 stats:{matches:"125 Tests",runs:"10,122 Test runs",avg:"51.12",era:"1971–1987"},
 fact:{en:"Gavaskar scored 774 runs in his very first Test series against West Indies in 1971 — he wasn't even supposed to tour, he was a late replacement.",
       hi:"गावस्कर ने 1971 में वेस्टइंडीज के खिलाफ अपनी पहली टेस्ट सीरीज़ में 774 रन बनाए — वे टूर पर जाने वाले भी नहीं थे, आखिरी वक्त पर शामिल हुए।"},
 moreFacts:{en:"He famously batted through 60 overs in the 1975 World Cup against England and scored just 36*. The reason remains a mystery to this day.",
            hi:"1975 विश्व कप में इंग्लैंड के खिलाफ उन्होंने 60 ओवर बल्लेबाज़ी की और मात्र 36* बनाए। आज तक यह रहस्य है कि क्यों।"},
 quiz:[{q:{en:"How many runs did Gavaskar score in his debut Test series?",hi:"गावस्कर ने डेब्यू टेस्ट सीरीज़ में कितने रन बनाए?"},
        o:{en:["574","674","774","874"],hi:["574","674","774","874"]},c:2,
        exp:{en:"Gavaskar scored 774 runs in his debut series against West Indies in 1971.",hi:"गावस्कर ने 1971 में वेस्टइंडीज के खिलाफ अपनी डेब्यू सीरीज़ में 774 रन बनाए।"}},
       {q:{en:"What was Gavaskar's nickname?",hi:"गावस्कर का उपनाम क्या था?"},
        o:{en:["The Wall","Sunny","Little Master","The Opener"],hi:["दीवार","सनी","लिटिल मास्टर","ओपनर"]},c:1,
        exp:{en:"Sunil Gavaskar was fondly called 'Sunny' by fans and teammates throughout his career.",hi:"सुनील गावस्कर को उनके करियर में प्रशंसकों और टीम के साथियों द्वारा प्यार से 'सनी' कहा जाता था।"}},
       {q:{en:"Gavaskar's Test career spanned from 1971 to which year?",hi:"गावस्कर का टेस्ट करियर 1971 से किस साल तक चला?"},
        o:{en:["1985","1986","1987","1988"],hi:["1985","1986","1987","1988"]},c:2,
        exp:{en:"Gavaskar played his last Test in 1987, playing for 16 years at the highest level.",hi:"गावस्कर ने 1987 में अपना अंतिम टेस्ट खेला, 16 साल तक उच्चतम स्तर पर खेलते रहे।"}}]},

{name:"Rahul Dravid",flag:"🇮🇳",country:"India",role:"Batter",
 tomorrow:{country:"India",role:"Off-spin bowler",era:"1990s–2010s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Middle-order batter · Right-hand · 'The Wall'",mono:false},
      {label:"Stat",type:"CLUE 2",value:"29,942 balls faced in Tests — most ever",mono:true},
      {label:"Era",type:"CLUE 3",value:"India · 1996–2012 · Karnataka",mono:true},
      {label:"Record",type:"CLUE 4",value:"Most catches ever by non-keeper: 210",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"मध्यक्रम बल्लेबाज़ · दाएं हाथ · 'दीवार'",mono:false},
      {label:"आँकड़ा",type:"सुराग 2",value:"29,942 गेंदों का सामना — टेस्ट में सर्वाधिक",mono:true},
      {label:"दौर",type:"सुराग 3",value:"भारत · 1996–2012 · कर्नाटक",mono:true},
      {label:"रिकॉर्ड",type:"सुराग 4",value:"गैर-विकेटकीपर द्वारा सर्वाधिक कैच: 210",mono:true}]},
 stats:{matches:"164 Tests · 344 ODIs",runs:"13,288 Test runs",avg:"52.31",era:"1996–2012"},
 fact:{en:"Dravid is the only player in history to score centuries in all 10 Test-playing nations. He batted every position from 1 to 8 for India.",
       hi:"द्रविड़ इतिहास के एकमात्र खिलाड़ी हैं जिन्होंने सभी 10 टेस्ट देशों में शतक बनाए। उन्होंने भारत के लिए 1 से 8 तक हर पोजीशन पर बल्लेबाज़ी की।"},
 moreFacts:{en:"In the legendary 2001 Kolkata Test, Dravid scored 180 in the second innings as India followed on — one of cricket's greatest ever partnerships with VVS Laxman.",
            hi:"2001 के ऐतिहासिक कोलकाता टेस्ट में, जब भारत फॉलो-ऑन कर रहा था, द्रविड़ ने दूसरी पारी में 180 रन बनाए — VVS लक्ष्मण के साथ क्रिकेट की सर्वश्रेष्ठ साझेदारियों में से एक।"},
 quiz:[{q:{en:"What is Rahul Dravid's famous nickname?",hi:"राहुल द्रविड़ का प्रसिद्ध उपनाम क्या है?"},
        o:{en:["The Rock","The Wall","Mr Dependable","Jammy"],hi:["रॉक","दीवार","मिस्टर डिपेंडेबल","जैमी"]},c:1,
        exp:{en:"Rahul Dravid earned the nickname 'The Wall' for his rock-solid defense and ability to bat through sessions.",hi:"राहुल द्रविड़ ने 'दीवार' का उपनाम अपनी अटूट रक्षात्मक बल्लेबाज़ी के लिए अर्जित किया।"}},
       {q:{en:"Dravid scored how many Test runs in his career?",hi:"द्रविड़ ने अपने करियर में कितने टेस्ट रन बनाए?"},
        o:{en:["12,288","13,288","14,288","11,288"],hi:["12,288","13,288","14,288","11,288"]},c:1,
        exp:{en:"Rahul Dravid scored 13,288 Test runs — second only to Sachin Tendulkar among Indians.",hi:"राहुल द्रविड़ ने 13,288 टेस्ट रन बनाए — भारतीयों में सचिन तेंदुलकर के बाद दूसरे।"}},
       {q:{en:"In the 2001 Kolkata Test, how many runs did Laxman score in the famous partnership with Dravid?",hi:"2001 कोलकाता टेस्ट में लक्ष्मण ने द्रविड़ के साथ प्रसिद्ध साझेदारी में कितने रन बनाए?"},
        o:{en:["200","241","281","300"],hi:["200","241","281","300"]},c:2,
        exp:{en:"VVS Laxman scored an iconic 281, sharing a 376-run partnership with Dravid to help India win from a seemingly impossible position.",hi:"VVS लक्ष्मण ने ऐतिहासिक 281 रन बनाए, द्रविड़ के साथ 376 रन की साझेदारी कर असंभव लगती स्थिति से भारत को जीत दिलाई।"}}]},

{name:"Don Bradman",flag:"🇦🇺",country:"Australia",role:"Batter",
 tomorrow:{country:"Australia",role:"Leg-spin bowler",era:"1990s–2000s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Right-hand bat · Middle order · Australia",mono:false},
      {label:"Average",type:"CLUE 2",value:"Test batting average: 99.94",mono:true},
      {label:"Era",type:"CLUE 3",value:"Australia · 1928–1948",mono:true},
      {label:"Legacy",type:"CLUE 4",value:"Greatest statistical achievement in any sport",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"दाएं हाथ का बल्लेबाज़ · मध्यक्रम · ऑस्ट्रेलिया",mono:false},
      {label:"औसत",type:"सुराग 2",value:"टेस्ट बल्लेबाज़ी औसत: 99.94",mono:true},
      {label:"दौर",type:"सुराग 3",value:"ऑस्ट्रेलिया · 1928–1948",mono:true},
      {label:"विरासत",type:"सुराग 4",value:"किसी भी खेल में सबसे महान सांख्यिकीय उपलब्धि",mono:true}]},
 stats:{matches:"52 Tests",runs:"6,996 Test runs",avg:"99.94",era:"1928–1948"},
 fact:{en:"Bradman needed just 4 runs in his final innings to average 100. He was bowled second ball for 0. Some say emotion caused his eyes to water.",
       hi:"ब्रैडमैन को अंतिम पारी में औसत 100 करने के लिए सिर्फ 4 रन चाहिए थे। वे दूसरी गेंद पर 0 पर बोल्ड हो गए। कुछ लोग कहते हैं भावनाओं ने उनकी आंखें नम कर दी थीं।"},
 moreFacts:{en:"His average of 99.94 is so far above any other player that statisticians call it the most extraordinary achievement in all sport. The next best is around 60.",
            hi:"उनका 99.94 का औसत किसी भी अन्य खिलाड़ी से इतना ऊपर है कि सांख्यिकीविद् इसे सभी खेलों की सबसे असाधारण उपलब्धि कहते हैं। दूसरा सर्वश्रेष्ठ लगभग 60 है।"},
 quiz:[{q:{en:"What did Bradman need in his final innings to average exactly 100?",hi:"ब्रैडमैन को अंतिम पारी में ठीक 100 औसत के लिए कितने रन चाहिए थे?"},
        o:{en:["6 runs","4 runs","2 runs","8 runs"],hi:["6 रन","4 रन","2 रन","8 रन"]},c:1,
        exp:{en:"Bradman needed just 4 runs to average 100. He was bowled for 0 by Eric Hollies, finishing at 99.94.",hi:"ब्रैडमैन को सिर्फ 4 रन चाहिए थे। एरिक होलीज़ ने उन्हें 0 पर बोल्ड कर दिया और वे 99.94 पर रह गए।"}},
       {q:{en:"How many Test matches did Bradman play?",hi:"ब्रैडमैन ने कितने टेस्ट मैच खेले?"},
        o:{en:["48","52","56","60"],hi:["48","52","56","60"]},c:1,
        exp:{en:"Don Bradman played 52 Test matches for Australia between 1928 and 1948.",hi:"डॉन ब्रैडमैन ने 1928 से 1948 के बीच ऑस्ट्रेलिया के लिए 52 टेस्ट मैच खेले।"}},
       {q:{en:"Bradman was knighted in which year?",hi:"ब्रैडमैन को किस वर्ष नाइटहुड दिया गया?"},
        o:{en:["1947","1948","1949","1950"],hi:["1947","1948","1949","1950"]},c:2,
        exp:{en:"Sir Donald Bradman was knighted in 1949, becoming one of cricket's most celebrated figures.",hi:"सर डोनाल्ड ब्रैडमैन को 1949 में नाइटहुड दिया गया।"}}]},

{name:"Shane Warne",flag:"🇦🇺",country:"Australia",role:"Bowler",
 tomorrow:{country:"West Indies",role:"Left-hand bat",era:"1990s–2000s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Leg-spin bowler · Australia · Right-hand bat",mono:false},
      {label:"Wickets",type:"CLUE 2",value:"708 Test wickets",mono:true},
      {label:"Era",type:"CLUE 3",value:"Australia · 1992–2007",mono:true},
      {label:"Ball",type:"CLUE 4",value:"Ball of the Century to Gatting — Ashes 1993",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"लेग-स्पिन गेंदबाज़ · ऑस्ट्रेलिया · दाएं हाथ",mono:false},
      {label:"विकेट",type:"सुराग 2",value:"708 टेस्ट विकेट",mono:true},
      {label:"दौर",type:"सुराग 3",value:"ऑस्ट्रेलिया · 1992–2007",mono:true},
      {label:"गेंद",type:"सुराग 4",value:"1993 एशेज़ में गैटिंग को 'सदी की गेंद'",mono:true}]},
 stats:{matches:"145 Tests",runs:"3,154 Test runs",avg:"25.41 bowling",era:"1992–2007"},
 fact:{en:"Warne's 'Ball of the Century' to Mike Gatting in 1993 — his very first ball in an Ashes Test — pitched outside leg stump and hit top of off. Gatting stood and stared in disbelief.",
       hi:"1993 में वार्न की गैटिंग को 'सदी की गेंद' — उनकी एशेज़ टेस्ट में पहली ही गेंद — लेग स्टंप के बाहर पिच होकर ऑफ स्टंप के ऊपर लगी। गैटिंग अविश्वास में खड़े रहे।"},
 moreFacts:{en:"He took 195 Ashes wickets — the most in Ashes history. He died suddenly of a heart attack in March 2022 aged 52, shocking the cricket world.",
            hi:"उन्होंने 195 एशेज़ विकेट लिए — एशेज़ इतिहास में सर्वाधिक। मार्च 2022 में 52 साल की उम्र में दिल का दौरा पड़ने से उनका अचानक निधन हो गया।"},
 quiz:[{q:{en:"What delivery did Warne bowl to dismiss Gatting in 1993?",hi:"1993 में वार्न ने गैटिंग को आउट करने के लिए कौन सी गेंद डाली?"},
        o:{en:["Googly","Flipper","Leg break","Doosra"],hi:["गुगली","फ्लिपर","लेग ब्रेक","दूसरा"]},c:2,
        exp:{en:"Warne bowled a traditional leg break — but the curve and dip made it seem supernatural.",hi:"वार्न ने पारंपरिक लेग ब्रेक डाली — लेकिन उसकी घुमाव और गिरावट अलौकिक लग रही थी।"}},
       {q:{en:"How many Ashes wickets did Warne take?",hi:"वार्न ने कितने एशेज़ विकेट लिए?"},
        o:{en:["155","175","195","215"],hi:["155","175","195","215"]},c:2,
        exp:{en:"Shane Warne took 195 Ashes wickets — the most by any bowler in the history of the series.",hi:"शेन वार्न ने 195 एशेज़ विकेट लिए — सीरीज़ के इतिहास में किसी भी गेंदबाज़ द्वारा सर्वाधिक।"}},
       {q:{en:"In which year did Shane Warne sadly pass away?",hi:"शेन वार्न का दुखद निधन किस वर्ष हुआ?"},
        o:{en:["2020","2021","2022","2023"],hi:["2020","2021","2022","2023"]},c:2,
        exp:{en:"Shane Warne died on March 4, 2022, aged 52, from a suspected heart attack in Thailand.",hi:"शेन वार्न का 4 मार्च 2022 को थाईलैंड में 52 वर्ष की आयु में संदिग्ध हृदयाघात से निधन हो गया।"}}]},

{name:"Brian Lara",flag:"🇹🇹",country:"West Indies",role:"Batter",
 tomorrow:{country:"Sri Lanka",role:"Off-spin bowler",era:"1990s–2000s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Left-hand bat · West Indies · Trinidad",mono:false},
      {label:"Records",type:"CLUE 2",value:"501* FC innings · 400* Test innings",mono:true},
      {label:"Era",type:"CLUE 3",value:"West Indies · 1990–2007",mono:true},
      {label:"Record",type:"CLUE 4",value:"Highest individual Test innings: 400*",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"बाएं हाथ का बल्लेबाज़ · वेस्टइंडीज · त्रिनिदाद",mono:false},
      {label:"रिकॉर्ड",type:"सुराग 2",value:"501* FC पारी · 400* टेस्ट पारी",mono:true},
      {label:"दौर",type:"सुराग 3",value:"वेस्टइंडीज · 1990–2007",mono:true},
      {label:"रिकॉर्ड",type:"सुराग 4",value:"सर्वोच्च व्यक्तिगत टेस्ट पारी: 400*",mono:true}]},
 stats:{matches:"131 Tests",runs:"11,953 Test runs",avg:"52.88",era:"1990–2007"},
 fact:{en:"Lara scored 501* for Warwickshire in 1994 — the highest score in all of cricket history. He also holds the Test record of 400* against England.",
       hi:"लारा ने 1994 में वॉरविकशायर के लिए 501* बनाए — पूरे क्रिकेट इतिहास का सर्वोच्च स्कोर। उनके पास 400* का टेस्ट रिकॉर्ड भी है।"},
 moreFacts:{en:"His 153* in a losing cause for West Indies against Australia in 1999 is widely regarded as one of the greatest batting performances under pressure.",
            hi:"1999 में ऑस्ट्रेलिया के खिलाफ हार में भी उनकी 153* पारी को दबाव में सर्वश्रेष्ठ बल्लेबाज़ी प्रदर्शनों में माना जाता है।"},
 quiz:[{q:{en:"What is Brian Lara's highest score in First Class cricket?",hi:"ब्रायन लारा का प्रथम श्रेणी क्रिकेट में सर्वोच्च स्कोर क्या है?"},
        o:{en:["400*","499","501*","503*"],hi:["400*","499","501*","503*"]},c:2,
        exp:{en:"Brian Lara scored 501* for Warwickshire against Durham in 1994 — the highest in all First Class cricket.",hi:"ब्रायन लारा ने 1994 में वॉरविकशायर के लिए डरहम के खिलाफ 501* बनाए — प्रथम श्रेणी क्रिकेट में सर्वोच्च।"}},
       {q:{en:"Against which country did Lara score his Test record 400*?",hi:"लारा ने किस देश के खिलाफ टेस्ट रिकॉर्ड 400* बनाया?"},
        o:{en:["Australia","South Africa","England","India"],hi:["ऑस्ट्रेलिया","दक्षिण अफ्रीका","इंग्लैंड","भारत"]},c:2,
        exp:{en:"Brian Lara scored 400* against England at Antigua in 2004.",hi:"ब्रायन लारा ने 2004 में एंटीगुआ में इंग्लैंड के खिलाफ 400* बनाया।"}},
       {q:{en:"What is Lara's Test batting average?",hi:"लारा का टेस्ट बल्लेबाज़ी औसत क्या है?"},
        o:{en:["49.50","51.00","52.88","54.50"],hi:["49.50","51.00","52.88","54.50"]},c:2,
        exp:{en:"Brian Lara finished with an average of 52.88 in Tests — one of the highest by any West Indian.",hi:"ब्रायन लारा ने 52.88 के औसत के साथ टेस्ट करियर समाप्त किया।"}}]},

{name:"Wasim Akram",flag:"🇵🇰",country:"Pakistan",role:"Bowler",
 tomorrow:{country:"India",role:"Right-arm fast bowler",era:"2000s–2020s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Left-arm fast · All-rounder · Pakistan",mono:false},
      {label:"Wickets",type:"CLUE 2",value:"916 international wickets combined",mono:true},
      {label:"Era",type:"CLUE 3",value:"Pakistan · 1985–2003",mono:true},
      {label:"Legacy",type:"CLUE 4",value:"Greatest left-arm fast bowler in cricket history",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"बाएं हाथ तेज़ · ऑलराउंडर · पाकिस्तान",mono:false},
      {label:"विकेट",type:"सुराग 2",value:"916 अंतरराष्ट्रीय विकेट",mono:true},
      {label:"दौर",type:"सुराग 3",value:"पाकिस्तान · 1985–2003",mono:true},
      {label:"विरासत",type:"सुराग 4",value:"क्रिकेट इतिहास के सर्वश्रेष्ठ बाएं हाथ तेज़ गेंदबाज़",mono:true}]},
 stats:{matches:"104 Tests · 356 ODIs",runs:"2,898 Test runs",avg:"23.62 bowling",era:"1985–2003"},
 fact:{en:"In the 1992 World Cup final, Akram bowled Allan Lamb and Chris Lewis in successive balls with unplayable reverse-swinging yorkers that turned the match completely.",
       hi:"1992 विश्व कप फाइनल में अकरम ने लगातार गेंदों पर एलन लैम्ब और क्रिस लुईस को अखेलने योग्य रिवर्स-स्विंगिंग यॉर्कर पर आउट कर मैच पलट दिया।"},
 moreFacts:{en:"His nickname was 'Sultan of Swing'. He could swing the ball both ways at over 140 km/h AND master reverse swing at will.",
            hi:"उनका उपनाम 'स्विंग का सुल्तान' था। वे 140+ किमी/घंटे पर गेंद को दोनों तरफ स्विंग करा सकते थे।"},
 quiz:[{q:{en:"What is Wasim Akram's famous nickname?",hi:"वसीम अकरम का प्रसिद्ध उपनाम क्या है?"},
        o:{en:["King of Swing","Sultan of Swing","Prince of Pace","Master of Reverse"],hi:["स्विंग का राजा","स्विंग का सुल्तान","पेस का राजकुमार","रिवर्स के उस्ताद"]},c:1,
        exp:{en:"Wasim Akram was called 'Sultan of Swing' for his mastery of conventional and reverse swing.",hi:"वसीम अकरम को पारंपरिक और रिवर्स स्विंग की महारत के लिए 'स्विंग का सुल्तान' कहा जाता था।"}},
       {q:{en:"How many Test wickets did Akram take?",hi:"अकरम ने कितने टेस्ट विकेट लिए?"},
        o:{en:["384","404","414","424"],hi:["384","404","414","424"]},c:2,
        exp:{en:"Wasim Akram took 414 Test wickets — the most by any Pakistani bowler.",hi:"वसीम अकरम ने 414 टेस्ट विकेट लिए — किसी भी पाकिस्तानी गेंदबाज़ द्वारा सर्वाधिक।"}},
       {q:{en:"In which city was Wasim Akram born?",hi:"वसीम अकरम का जन्म किस शहर में हुआ?"},
        o:{en:["Karachi","Lahore","Rawalpindi","Faisalabad"],hi:["कराची","लाहौर","रावलपिंडी","फैसलाबाद"]},c:1,
        exp:{en:"Wasim Akram was born in Lahore, Pakistan on June 3, 1966.",hi:"वसीम अकरम का जन्म 3 जून 1966 को लाहौर, पाकिस्तान में हुआ।"}}]},

{name:"Muttiah Muralitharan",flag:"🇱🇰",country:"Sri Lanka",role:"Bowler",
 tomorrow:{country:"India",role:"Wicket-keeper batter",era:"2010s–2020s"},
 clues:{
  en:[{label:"Role",type:"CLUE 1",value:"Off-spin bowler · Sri Lanka",mono:false},
      {label:"Record",type:"CLUE 2",value:"800 Test wickets — world record",mono:true},
      {label:"Era",type:"CLUE 3",value:"Sri Lanka · 1992–2010",mono:true},
      {label:"Farewell",type:"CLUE 4",value:"Took 800th wicket on the final ball of his last Test",mono:true}],
  hi:[{label:"भूमिका",type:"सुराग 1",value:"ऑफ-स्पिन गेंदबाज़ · श्रीलंका",mono:false},
      {label:"रिकॉर्ड",type:"सुराग 2",value:"800 टेस्ट विकेट — विश्व रिकॉर्ड",mono:true},
      {label:"दौर",type:"सुराग 3",value:"श्रीलंका · 1992–2010",mono:true},
      {label:"विदाई",type:"सुराग 4",value:"अंतिम टेस्ट की आखिरी गेंद पर 800वां विकेट",mono:true}]},
 stats:{matches:"133 Tests",runs:"1,261 Test runs",avg:"22.72 bowling",era:"1992–2010"},
 fact:{en:"Muralitharan was called for throwing by Australian umpire Darrell Hair in 1995. Multiple biomechanical studies proved his unusual action was due to a physical deformity — not cheating.",
       hi:"1995 में ऑस्ट्रेलियाई अंपायर डेरेल हेयर ने मुरलीधरन पर थ्रोइंग का आरोप लगाया। कई बायोमेकेनिकल अध्ययनों ने साबित किया कि उनकी अनोखी एक्शन एक शारीरिक विकृति के कारण थी।"},
 moreFacts:{en:"He took his 800th wicket on the very last ball of his final Test match — a fairytale ending. His doosra was specifically developed to dismiss left-handed batters.",
            hi:"उन्होंने अपने आखिरी टेस्ट मैच की आखिरी गेंद पर 800वां विकेट लिया — एक परी-कथा जैसा अंत। उनका दूसरा बाएं हाथ के बल्लेबाज़ों को आउट करने के लिए विकसित किया गया था।"},
 quiz:[{q:{en:"Who did Murali dismiss to take his 800th Test wicket?",hi:"मुरली ने 800वां टेस्ट विकेट किसे आउट करके लिया?"},
        o:{en:["MS Dhoni","Zaheer Khan","Pragyan Ojha","Ishant Sharma"],hi:["MS धोनी","ज़हीर खान","प्रज्ञान ओझा","इशांत शर्मा"]},c:2,
        exp:{en:"Muralitharan dismissed Pragyan Ojha on the final ball of his career to reach exactly 800 wickets.",hi:"मुरलीधरन ने अपने करियर की आखिरी गेंद पर प्रज्ञान ओझा को आउट कर ठीक 800 विकेट पूरे किए।"}},
       {q:{en:"Which umpire no-balled Murali for throwing in 1995?",hi:"1995 में किस अंपायर ने मुरली को थ्रोइंग के लिए नो-बॉल दिया?"},
        o:{en:["Steve Bucknor","Darrell Hair","Billy Bowden","Ross Emerson"],hi:["स्टीव बकनर","डेरेल हेयर","बिली बाउडेन","रॉस एमर्सन"]},c:1,
        exp:{en:"Darrell Hair called Muralitharan for throwing in Melbourne in 1995 — a controversial decision widely disputed.",hi:"डेरेल हेयर ने 1995 में मेलबर्न में मुरलीधरन पर थ्रोइंग का आरोप लगाया — एक विवादास्पद निर्णय।"}},
       {q:{en:"What unique delivery did Murali develop?",hi:"मुरली ने कौन सी अनोखी गेंद विकसित की?"},
        o:{en:["Flipper","Googly","Doosra","Carrom ball"],hi:["फ्लिपर","गुगली","दूसरा","कैरम बॉल"]},c:2,
        exp:{en:"Muralitharan developed the doosra — a ball that spins the other way from an off-break — primarily to dismiss left-handed batters.",hi:"मुरलीधरन ने दूसरा विकसित किया — एक गेंद जो ऑफ ब्रेक से उल्टी दिशा में मुड़ती है — मुख्यतः बाएं हाथ के बल्लेबाज़ों को आउट करने के लिए।"}}]},
];

// Get today's puzzle based on date seed
function getDailyPuzzle(dateStr) {
  const seed = [...dateStr].reduce((a,c)=>a+c.charCodeAt(0),0);
  return PUZZLES[seed % PUZZLES.length];
}

// Get puzzle for a specific index (practice mode)
function getPracticePlayer(index) {
  return PUZZLES[index % PUZZLES.length];
}
